<template>
  <view>
    <view class="uni-padding-wrap uni-common-mt">
      <button type="default" v-for="item in deviceList" :key="item.deviceId" @click="testPrint(item.deviceId)">
        {{ item.name + '   (' + item.RSSI + ')' }}
      </button>
    </view>
    <view>
      <scroll-view scroll-x="true" scroll-y="true" style="width: 0; height: 0;">
        <canvas id="myCanvas" canvas-id="myCanvas" style="width: 2480px; height: 3510px;"></canvas>
      </scroll-view>
    </view>
  </view>
</template>

<script>
const Bluetooth = require("../../util/bluetooth.js");
const CPCL = require("../../util/CPCL.min.js");
const HEX = require("../../util/HEX.min.js");
export default {
  data() {
    return {
      device: undefined,
      deviceList: [],
    };
  },
  onLoad() {
    // #ifndef H5
    let that = this;
    this.deviceList = [];
    // 搜索蓝牙设备
    Bluetooth.find(function (res) {
      for (const item of res.devices) {
        if (!item.name) continue;
        let bol = true;
        for (const device of that.deviceList) {
          if (item.deviceId === device.deviceId) {
            bol = false;
            break;
          }
        }
        bol && that.deviceList.push(item);
      }
    });
    // #endif
  },
  methods: {
    // imgPath -> CanvasImageData
    async imgPath2CanvasImageData(imgPath, { width, height, rotate90 }) {
      // 获取图片信息
      let imgInfo = await new Promise((resolve, reject) => {
        uni.getImageInfo({src: imgPath, success: resolve});
      })
      const imgWidth = imgInfo.width;
      const imgHeight = imgInfo.height;
      // 等比缩放图片
      if (width && height) {
        // 同时指定宽和高，根据宽度或高度等比例缩放
        const ratio = Math.min(width / imgWidth, height / imgHeight);
        width = Math.floor(imgWidth * ratio);
        height = Math.floor(imgHeight * ratio);
      } else if (width) {
        // 指定宽度，根据宽度等比例缩放
        height = Math.floor(imgHeight * (width / imgWidth))
      } else if (height) {
        // 指定高度，根据高度等比例缩放
        width = Math.floor(imgWidth * (height / imgHeight))
      } else {
        // 不指定，使用原图宽高
        width = imgWidth;
        height = imgHeight;
      }
      if (rotate90) {
        [width, height] = [height, width];
      }
      // 获取在画布上绘图的环境
      const ctx = uni.createCanvasContext('myCanvas');
      // 填充白色底色，否则透明png图片打印出来会全黑
      ctx.setFillStyle('white')
      ctx.fillRect(0, 0, width, height)
      if (rotate90) {
        // 将画布原点移动到旋转中心
        ctx.translate(width / 2, height / 2);
        // 画布旋转90度
        ctx.rotate(Math.PI / 2);
        // 将画布原点移回左上角
        ctx.translate(-height / 2, -width / 2);
        // 将图片绘制到画布上
        ctx.drawImage(imgPath, 0, 0, height, width)
      } else {
        // 将图片绘制到画布上
        ctx.drawImage(imgPath, 0, 0, width, height)
      }
      // // 将图片绘制到画布上
      // ctx.drawImage(imgPath, 0, 0, width, height)
      await new Promise((resolve, reject) => ctx.draw(false, resolve))
      // 获取画布上的图像像素矩阵
      return new Promise((resolve, reject) => {
        uni.canvasGetImageData({
          canvasId: 'myCanvas',
          x: 0,
          y: 0,
          width: width,
          height: height,
          success: resolve
        })
      })
    },
    // 生成图片并获取Canvas的ImageData
    async generateCanvasImageData() {
      // 定义画布宽高
      const width = 400
      const height = 200
      // 获取在画布上绘图的环境
      const ctx = uni.createCanvasContext('myCanvas');
      // 填充白色底色，否则透明png图片打印出来会全黑
      ctx.setFillStyle('white')
      ctx.fillRect(0, 0, width, height)
      // 在画布上绘制被填充的文本
      ctx.setFillStyle('black')
      ctx.setFontSize(20)
      ctx.fillText('Hello', 20, 50)
      ctx.setFontSize(26)
      ctx.fillText('Winford', 100, 100)
      ctx.setStrokeStyle('black')
      ctx.strokeRect(80, 60, 130, 60)
      // 更多使用示例参考官方文档：https://uniapp.dcloud.net.cn/api/canvas/CanvasContext.html

      await new Promise((resolve, reject) => ctx.draw(false, resolve))
      // 获取画布上的图像像素矩阵
      return new Promise((resolve, reject) => {
        uni.canvasGetImageData({
          canvasId: 'myCanvas',
          x: 0,
          y: 0,
          width,
          height,
          success: resolve
        })
      })
    },
    // 使用SDK(CPCL.js)构建指令
    async cpcl0() {
      uni.showLoading({
        title: '正在处理图片...',
        mask: true,
      });
      // === 本地图片打印 ===
      // let imgPath = "../../../static/test.jpg"
      // let imgPath = "../../../static/test1.jpg"
      // let imgPath = "../../../static/a4.jpg"
      // === 选择图片打印 ===
      // let imgPath = await new Promise((resolve, reject) => {
      // 	uni.chooseImage({
      // 		count: 1,
      // 		sizeType: ['original'],
      // 		success: res => resolve(res.tempFilePaths[0])
      // 	})
      // })
      // === 网络图片打印 ===
      // let url = 'https://web-assets.dcloud.net.cn/unidoc/zh/uni@2x.png'
      // let imgPath = await new Promise((resolve, reject) => {
      // 	uni.downloadFile({
      //      url: url,
      // 		success: res => resolve(res.tempFilePath)
      // 	})
      // })
      // === BASE64编码图片打印 ===
      // 数据中不能包含前缀，如："data:image/png;base64,"
      // let base64 = "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAAXNSR0IArs4c6QAAAglJREFUWEfNmFGOgzAMRJOTlZ6M9mS0J8tqkIxSGnsmgV2Wv6rBeR7Hxk4upZQkPq/XKz2fz201ftszTVO63W7rz8fjIVrky7ICiA3f73eqgZjpeZ5PgQ0BAXS/3xlL+D9AjyjqAsJoHc5DlCmlUdAmIFTrCacKPwL5BfhbcOZEL+QHoBpWZCwebGZK9yTRsizJbDD1N0AFTvFesQM4QCrPBphzdtfDIOBUr60WRkmmOAs7KyDzuqOWfzh5ht0VMFJP9dSTP0o65SzmZVmKV4yPwgE6KvbKWczzPBfvrIyGdq9mpCLbI0/TVFpFWfFOyUKmIguzC3hGeM2BKMwUMKXUbLfOBFzLhVPG2D4ofk1A5pkaXlvnnUMK6J1B9mIvoKcgE+LyJBnOYijEXlZVjL4obI+wUDP5jwIqpSz81CkGGGSknnLOV8Co0itGPEg207Dwbt0MMzQCaSOqNzqoNrd+kLX6qkGlF+xJwA2QqVjPFAZRh9aUQuPBBq4eZz9mEhWyBkMiMaD9Ge25hfia6lgXzLK293+mZnMu/k+Q7s3CSLg99aASG0s9Jenl0RE1601ZlYBzLUgKaKrYBRC7r6mH+npMVSOyh5QBWyXFstdA2NysRqOGHALszdR6fS/knwOqXxqsQzd1CaAKiSNzGaACibN4KSCDvDTELHGsm79cwbrOosbur/p+AOSh+VvOQpJrAAAAAElFTkSuQmCC"
      // let imgPath = `${wx.env.USER_DATA_PATH}/tmp_${new Date().getTime()}`;
      // 写入文件，用完记得删除：uni.getFileSystemManager().unlink({filePath: imgPath})
      // #ifdef MP-WEIXIN || MP-QQ || MP-TOUTIAO
      // await new Promise((resolve, reject) => {
      // 	uni.getFileSystemManager().writeFile({
      // 		filePath: imgPath,
      // 		data: base64,
      // 		encoding: 'base64',
      // 		success: resolve,
      // 		fail: reject
      // 	})
      // })
      // #endif

      // 获取ImageData
      // let canvasImageData = await this.imgPath2CanvasImageData(imgPath); // 图片原始尺寸
      // let canvasImageData = await this.imgPath2CanvasImageData(imgPath, { width: 1600 }); // 指定宽等比缩放图片
      // let canvasImageData = await this.imgPath2CanvasImageData(imgPath, { height: 1600 }); // 指定高等比缩放图片
      // let canvasImageData = await this.imgPath2CanvasImageData(imgPath, { width: 1680, height: 2376 }); // 指定宽高等比缩放图片
      // let canvasImageData = await this.imgPath2CanvasImageData(imgPath, { rotate90: true }); // 指定宽高等比缩放图片
      // 删除BASE64临时保存的文件
      // uni.getFileSystemManager().unlink({filePath: imgPath})

      // === Canvas生成图片打印 ===
      let canvasImageData = await this.generateCanvasImageData();

      console.log('canvasImageData => ', canvasImageData.width, canvasImageData.height);
      uni.showLoading({
        title: '正在生成指令...',
        mask: true,
      });
      // 构建CPCL指令，更多使用方式见cpcl-sdk-demo-js，下载地址：http://open.lingmoyun.com/#/sdkDownload
      console.log('cpcl start => ', new Date());
      const dpi = 203; // 打印机DPI
      // 构建CPCL指令               整体偏移量 高度 打印份数
      let cpcl = CPCL.Builder.createArea(0, 2376, 1)
          // 任务ID，这里传什么打印结果会原样携带返回
          .taskId('1')
          // 固定写法，无需修改
          .pageWidth(dpi == 203 ? 1728 : 2592)
          // 打印图片 Canvas的ImageData x y
          .imageGG(canvasImageData, 0, 0) // 小程序调试模式下比较耗时，体验版、正式版正常。
          .formPrint()
          .build();
      console.log('cpcl finish => ', new Date());
      console.log('cpcl => ', cpcl.byteLength);
      console.log(HEX.ab2hex(cpcl))
      uni.hideLoading();
      return cpcl;
    },
    // 纯手写指令
    cpcl1() {
      let cpclStr = '! 0 200 200 1040 1\n' +
          'TEXT 55 3 130 40 物流发货单（普运）\n' +

          'TEXT 24 0 70 100 单号:\n' +
          'TEXT 24 0 155 100 6101622\n' + //单号值

          'TEXT 24 0 305 100  货号:\n' +
          'TEXT 24 0 390 100  101521-1-383\n' + //货号值

          'TEXT 24 0 70 140  起站:\n' +
          'TEXT 24 0 155 140  北城\n' + //起站值

          'TEXT 24 0 305 140  电话:\n' +
          'TEXT 24 0 390 140  18000000000\n' + //起站电话

          'TEXT 24 0 70 180  到站:\n' +
          'TEXT 24 0 155 180  宜宾\n' + //到站值

          'TEXT 24 0 305 180  电话:\n' +
          'TEXT 24 0 390 180  18000000000\n' + //到站电话

          'TEXT 24 0 70 220  收货人:\n' +
          'TEXT 24 0 170 220  收货人值\n' + //收货人值

          'TEXT 24 0 305 220  电话:\n' +
          'TEXT 24 0 390 220  18000000000\n' + //收货人电话

          'TEXT 24 0 70 260  发货人:\n' +
          'TEXT 24 0 170 260  发货人值\n' + //发货人值

          'TEXT 24 0 305 260  电话:\n' +
          'TEXT 24 0 390 260  18000000000\n' + //发货人电话

          'TEXT 24 0 70 300  编码:\n' +
          'TEXT 24 0 170 300  编码值\n' + //编码值

          'TEXT 24 0 305 300  日期:\n' +
          'TEXT 24 0 390 300  2021-4-18\n' + //日期

          'LINE 51 350 550 350 2\n' +
          'TEXT 24 0 70 370 货物名称：\n' +
          'TEXT 24 0 180 370  货物名称值\n' + //货物名称值

          'TEXT 24 0 310 370 件数：\n' +
          'TEXT 24 0 420 370  件数值\n' + //件数值

          'TEXT 24 0 70 420 重量：\n' +
          'TEXT 24 0 180 420  重量值\n' + //重量值

          'TEXT 24 0 310 420 体积：\n' +
          'TEXT 24 0 420 420  体积值\n' + //体积值

          'TEXT 24 0 70 470 运费：\n' +
          'TEXT 24 0 180 470  运费值\n' + //运费值

          'TEXT 24 0 310 470 快件费：\n' +
          'TEXT 24 0 420 470  快件费值\n' + //快件费

          'TEXT 24 0 70 520 保价金额：\n' +
          'TEXT 24 0 180 520  保价金额值\n' + //保价金额值

          'TEXT 24 0 310 520 保价费：\n' +
          'TEXT 24 0 420 520  保价费值\n' + //保价费费

          'TEXT 24 0 70 570 叉车费：\n' +
          'TEXT 24 0 180 570  叉车费值\n' + //叉车费值

          'TEXT 24 0 310 570 垫付款：\n' +
          'TEXT 24 0 420 570  垫付款值\n' + //垫付款值

          'TEXT 24 0 70 620 送货费：\n' +
          'TEXT 24 0 180 620  送货费值\n' + //送货费值

          'TEXT 24 0 310 620 已付合计：\n' +
          'TEXT 24 0 420 620  已付合计值\n' + //垫付款值

          'TEXT 24 0 70 670 代收款：\n' +
          'TEXT 24 0 180 670  代收款值\n' + //送货费值

          'TEXT 24 0 310 670 付款方式：\n' +
          'TEXT 24 0 420 670  付款方式值\n' + //付款方式值

          'TEXT 24 0 70 720 货到付款：\n' +
          'TEXT 24 0 180 720  货到付款值\n' + //货到付款值

          'TEXT 24 0 310 720 提货方式：\n' +
          'TEXT 24 0 420 720  提货方式值\n' + //提货方式值

          'TEXT 24 0 70 770 备注：\n' +
          'TEXT 24 0 180 770  备注值\n' + //备注值

          'TEXT 24 0 70 850 重要提示：本公司不收国家禁运货物，包括险品\n' +
          'TEXT 24 0 70 880 同时，请保价运输，没有保价货物，按照单价丢\n' +
          'TEXT 24 0 70 910 货物运费的最高5倍赔偿（货损除外）。\n' +
          'FORM\n' +
          'PRINT\n';
      let cpcl = HEX.str2ab(cpclStr);
      return cpcl;
    },
    async connect(deviceId) {
      if (
          this.device &&
          this.device.deviceId === deviceId &&
          this.device.connected
      ) {
        console.log('---已连接')
        return; // 已连接
      }

      this.device && this.device.close();

      console.log('---正在连接')
      // 蓝牙连接状态监听
      let onBLEConnectionStateChange = function (res) {
        if (res.connected) {
          console.log(`${res.deviceId}连接成功`);
        } else {
          console.log(`${res.deviceId}断开连接`);
        }
      };

      // 蓝牙数据监听
      let resJsons = [];
      let buf = undefined;
      let onBLECharacteristicValueChange = function (res) {
        let buffer = res.value; // ArrayBuffer
        let data = new Uint8Array(buffer);
        let hex = HEX.ab2hex(buffer);
        console.log(`收到数据(hex)--->${hex}`);
        let str = HEX.ab2str(buffer);
        console.log(`收到数据(str)--->${str}`);

        // *****粘包处理开始**************************************************************************
        for (let i = 0; i < data.byteLength; i++) {
          const b = data[i];
          if (buf) {
            buf.push(b);
          }
          if (b === 0x7B) { // '{'
            buf = [b];
          }
          if (b === 0x7D) { // '}'
            let jsonStr = HEX.ab2str(new Uint8Array(buf).buffer);
            resJsons.push(jsonStr);
            buf = undefined;
          }
        }
        // *****粘包处理结束**************************************************************************

        let jsonStr;
        while (jsonStr = resJsons.shift()) {
          let resJson = JSON.parse(jsonStr);
          let taskid = resJson.taskid;
          let printMsg = resJson.printMsg;

          if (printMsg === '77') { // 77表示打印机收到指令，开始打印
            console.log(`taskid=${taskid} print start.`);
            uni.showLoading({
              title: '正在打印...',
              mask: true,
            });
          } else { // 打印机打印结果回复
            const printSuccess = printMsg === '0';
            uni.hideLoading();
            if (printSuccess) { // 打印成功
              console.log(`taskid=${taskid} print successed.`);
              uni.showModal({
                content: '打印成功',
                showCancel: false,
              });
            } else { // 打印失败
              console.log(`taskid=${taskid} print err, code=${printMsg}.`);
              uni.showModal({
                content: '打印失败，err=' + printMsg,
                showCancel: false,
              });
            }
          }
        }
      };

      // 连接
      this.device = await Bluetooth.connect({
        deviceId,
        onBLEConnectionStateChange,
        onBLECharacteristicValueChange,
      });
    },
    async testPrint(deviceId) {
      uni.showLoading({
        title: '正在连接蓝牙...',
        mask: true,
      });
      await this.connect(deviceId);

      // CPCL指令
      let cpcl = await this.cpcl0();
      // let cpcl = this.cpcl1();
      // let cpclBase64 = 'ISAwIDIwMyAyMDMgMTY4MCAxClRBU0tJRCAxClBXIDE2ODAKR0cgMjEwIDE5IDEwIDEwIDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMjkgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCA0OCA0MiACAAAAAAAgAAAAAAAAAAAAAAAAAAAAchAACgAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDY3IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgODYgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxMDUgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxMjQgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxNDMgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxNjIgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxODEgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAyMDAgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAyMTkgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAyMzggNjM3IAIAAAAAACAAAAAAJhAAAwHAAABwHCchEQcnJACAAQJwAAABwGgElAEghBAADQHBwcAAeBwAADgH///AOADlGji0FwFwAAADhRoDlQMA3ASwAyB1FAABAeHDwIw0AzwP///AfGQaAx////gAPnoBAABlGoBsNGQajAKcBCB1LAOUEgh/8PHHgADwHAAAP2kYPydEAwE/j///f1EAAANkGgL/8///wIwCnASMByB1EAACf/B5xwCEGgcPjwABwA+////gjjQfxy1EAwWDwcAfz///wJwEIHUwA5QSDQcAMc4AAeAcAIAHzwABwAdkGgQAcAB4AAfAnAMBcAAAB2w0An/zgcHAjAKcBIwDIHUQAAEGAAHAZxoBwAFvNAEAH4hNAXAAAYCAFgpwAYAH/8HAAAcDgcHAjAKcBIwDIHUQAAkOA///8APAHAPgAA9zGwA/4HmB8PcVcAPAKEQDsAK8BKwBIHIWAA4HphoHwMQaBH/wAABwAeDoFQF4B8APJ4wGsAIgg0QDAgeAHAeAxhr3eClEAwR//HgPgA8DlE6AhWwaIH9EAwYAD/AAB4AcDwCkGgQD5z4AAHADuIIJAH/8fB8ADgHB2AAHfNF8GdwEqAEgcxQACBwAH/wAD4AcHgBgfNEDYA+HD4AAZBoLYD////B//Hw+AB4DwfykGowCnAQgcygDzBIIHAA93gAfgBx8APhkGgjwPwcH8AB4B4AA+GQaBgA4fPgAHgOB3qydjAKcBNQHIHMYAAABH+D5z4AfgBz4AP4PAAAA/HwHAWca/4D+pBoEf/AAPgOBz6QajAKcBCA7KAMAAQAAAAAAAAAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDI1NyA5OTMgAgAAAAAAIAYQAAAcP+Phw+A/gB3wAD8PAAAAPngAAGAA/Af/gD+B4AAAAHh/4AA+A4HHgAcDgcHAP2wCnAQgBnQBIFOYAAg/58HB8H+AH+AAH2QaAh4n//8AhhoPAYQaCnfAAH4DgcPAf/OBwcCMApwEIFOoAiAGzAEOfGcBwHD7gB/AAAYPHAAABgdkGgL+AA8AA4QaBnB3gAB+B4HB4IQajAKcBCAGdAEgU5gADXxmYccA84AfgAAADxwAwACEGgAG7gAPAAABwAAAAPBzgAD3BwHB8H/z///ArAKcBCBTrAIgBcwBBvxg4AcA44A+AGQaCAHgAAcABwAA7wAOJ0QDBsAA5wcBwOAHAylEA5g3IAV8ASBRlACHGsOA/IYaB8CEGgACAeeAHgAAA8AAAAHgceAA548BwECkGmwCAQAPHAd4NyBRrAIgBcQBBNxh/n/wQ4GmGh+A5BoEPAAAA///gIcaQ44BZB10UG8CAA8cbFQgBXgBIFKUAIQaBgOH/AAABg4cfqSDAwHDwDwAAnQXBAPAcPAAA57kGowCnAQgUqQCIAfIAQ0cY4YHAAOf3AAABw4d/AAHZIMOA8HgeAADg///gAPAcHgAAd7kGowCnAQgB3gBIFKfABxjjmUaHGQaAR/wAA9kgw4DwfDwAAeAAAOAB4BwPAAB/OQarwIOH/AgUqACIAjIAQ0cZw5nAAOOHABgDw4fwAAOhxqA+fBongUDgA8AcD4AAIQabJ0CBwAAA4CcBCAIfAEgUaAACxxujOcAA4AcAHAODh8ApxoHgH94uAcAB4AfAHAfAAD4bDQGA///4AcAAAeAnAQgUaACIAjHARxv/OQaAR4cAGCMNAEPAD/AbOwEB4AeAHAPgChFAw+EGnwEIAh8ASBRogAcZOQaAx4eHABwHmSDAQ8AH4Bs7AQHgDwAcAfgv2hwAcCsApwEIFGgAiAIxAECH+B4//CUTgMcHBwAcBxlGh5tNA58MQl4AHAD8AP+AcAAD/DkGpwEIAh8ASBRowAf4DinGvA8PGQaZBAAAz4Af/AAHgAABwDwAHAB8AfPgcAA/2QajAKcBHgEIHYMAAYf4HAHAAOAHgCGGvA8eBQCfAH5/AB8uQwA4ADwAOAPh/AAAP+AAcCsAmQaIHv5FhwipCoIA4AfAeA4eB4A4DhkGgADeAfw/wA8AAAPAGAA8AAgHwP/wAD8ItwtjAKcBHgEIHYPABwB4Gw0ABQP/+B4eB//4Hh////w8D/AP/A8AB//AAA/8AAAPgD///DAD///8IwCnAQgOzQDAAEAAAAAAAAAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAyNzYgMTk1IAIAAAAAACAGEAAJGAfABwADgA//wHjwcAAACn////Dw/wAP8DgAH/4AAD/gAAD8AB//8AAP//+sApwEIAZ0ASBUmgAPgGQaBgP/gHDwB/+AcGQaBmD8AAPweAAf/Kca8AABxBqMApwEIFSoAiAG0gEGAGQaAgAAABBgcACUBgJwAABgGIQBAT8AAAB8ApEBAIwCnAS8ASCJFQBAIImoAiAAAAAAAAAAAAAAAAAPpAINAAAAAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMjk1IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMzE0IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMzMzIDMwMSACAAAAAAAgAAAAAAAAAH8RABgxZR4EMUwAIIlJABzrFXAAcOgBAx4AAABwB/QBII8cADJFAw9kGnAAII8wA5wVAAIcAAA//////ADwAHAAH/z///AAAHIZcA6YAyCCEAAOeAAPDwAPgAeABwAP//wAADzkGgLgAHAAP6QaAQeAAAggkkUDH2QaAw/////wH4w0pBoB4HBwB3kBDiCSRQM/J0QDAwAAeAAAAWYaA8AoRAMngA0gf+AJCHgADweAH8AHAH8AiU48YRZwxRoBhBoGgAAAAA5wH//4aAMggQwAhBoDHcAPAPcAjDOIMWQaAf/wcADEGgMGAAAMcD8gj0YDAecpRAMB8AAAAyhEAwOGBwYAD/4gS0QDDgAAAAAAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAzNTIgNzIyIAIAAAAAACAGEAAAGngADweAHcAOAccAAABwAAAcAAAH////4AP/8HAAAcD///AHhwcPAB//ccY4IAZIASBemAAAAXgADwOAPeAOAQcAAADwA////8BkGgLwA4Bwd8QaAo4PB4AfII1EAwLAOOAeAGUa4GUa4IQaAgeAcH+ArDQEjg4DwBxw4SCLjAblGgGEGgAIwAcHgODwB4Dwd4ABwOBwcAeODgGAHHHhjjggXjgJIAb4AQV4AA8BwDjwHG40AcC8aAYHAODwD4Dwc8CkGgSf///4OHHDIIxFA3ClGgMrRwPgceAnRQP8II5EAwHgcHA8bjQDgCiMBgQfgOBw8B/8dE4Fn////DhwAw4ghtQJAX///wHkGmua///8nGgCH8HgcHikGgWAPAAAEHAHDCCJRAMCAOBwcDhsNCdEAwf/4PA9weBwPB/8fdGAaxlwBxx4ACAGdA4gW5gABH///wDg8HiEGgEPAB//jDQF/+DwOcHAcDi0t4QaAXMOHDAgW5wCIAnsAQV4AA8A8OA4eGw0BA8AAAD8AACUTgI54cBwEMQaBXgAAAB/HhxwIAlUASBbpAAqRAMFHgAAAe4AQAd3txDjwCIUJAkAcAAHgH//4AD/HDggikQDAXDgOHBsNAQeAAADzgDghxoA84AnRAMD///gB/w8IItHA3HgPIQaAzwAAAeHA8UadydEAwUB+AHAP/B4eCCKjwZ5wBzkGgEfB4fArjR/AOw0BQH4A8A/8PBwII1FA/B0Tgt4AAA+A5+ABwf/4PAAP4QaCf//+AcD/AeAPHHg8CCKRAMBOcAc4MQaAf4B/gClGj4nRAMFB5wHgBBzwOAgikcDO8AehBoDcAAD/gH4tbcAKEQDBA8ODwAAcYEgi0cDP4APhBoC8AAf7gBkGgEA4PAAnGgK3ABwAA8fD74AAHADwCBLjAYMAAAAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAzNzEgMzU3IAIAAAAAACAGEAAAGngADwA/gA/AAAcAAeAAP44AfAAHBwDg8AD/wHAAAf4AcAAOPgf8AABwB4BwIAZIASBemABlGh8nRAMBPg4CP6QaAwHz8HAAP4QaBHwD+AAAcA8gk0QDAAHAABgODg/ABweA4PAD4fwAAD/wbTT4hxofAHAgXvAFIAb4AY40AAd0TgAQA8AAAA5/B/wH////8AfA//wAPwAAcAAecB//AABwPgDwACAGTAEgXZgAD3AADgAPAAeAAAcAA4AAAA/+AaQaAAIPgD///BAD///8HCB/H+AAcHx/4CBdpAIgFvQBAR/4AHiMNA8/AAf//AAD///+PAf8D/wAcHggl0QDCcAACAcAAADwPgAAH4QaCPw4D/AB/ABwMD+AIBaUBCBd2AABHgAAAIUaGCccAgIYB4AAeCCHWBAn1AIgAAAAAAAAAACrIAANAAAAAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMzkwIDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNDA5IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNDI4IDE4NiACAAAAAAAgAAAAAAAAAAAAADMSAAOAIK8sKSCrRAMD/////wAAIGZEAwIB8AAD4NVFfNwAIBAYACBsRAMEB/wAD/gAAXAaBQP/AAA8AAAPYBoCDwAf//hgASAEDAAgbEQDAh//AD/+pBoCB/+AAHjFGh8gDEUD4JQGIGbUCQs/HwB+PgADwAAAAA/HwGUaH3kyfyANRAMBAcAHAWA1ICO0EwACAAAAAAAAAAAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDQ0NyA3NTAgAgAAAAAAIAYQAAABPAeAeA8AA4AAAAAPAeAA8AAAP2QHAv8AAAB4YAEgBAwABuADwAcB/////3gIIATEACA6kAAEeAeA8A+AB2oRHgAnRAMDAe8AAABwIAjYAWUaAGQaIAjEACA6oAAEeAPA8AeAD2QMDBwA8AHgAAB/AAAAAc8AAHw1eAIgAgwAhxoAD/AgAqgAIEGIAAFwA8DgxBoCPADwAcDFGo8gEkUDDiAJUAcgPFwDAwPAAAeAHmgMBDwAcAPAAABgTgEBDwAAfDV4AiACDAAF5///xwAAHjggAqgAIEKIAIUaHGANZhqAAIloACATRgM8PHQIIGEMAAIDgAAHgIwRAjwAcAeAqGhkGnw1IAZ4Ar1ofIQ9IAbIACA6mAACB4AADwCcRQQ8AHAPAAADcIIgFEYD+A9kpiA6qAIgBmgBAQ+AAB+ozwQ8AHAOAAADcIJkGoS6IAUQAYw0AQP4B8AgBbgAID2UAAQB/wAD/gB3YK8EPABwH/wAByAXRwMP/gN0CCA9uAIgAnQBCAH8AAP4AP/8AAAAZxr/AA+M0wEPAAAHIAL0AMgEjDQBP58B/twBIFwYAAQB/gAD/AD/bBEDPABwP/+AJ0QDhBsgBWwCBuD//wcB/w+AfyBj2AkIAf+AA/8B+B8D//hkGgEHwB4PfBsBDwAADiAFNAN0BGQaAgP8A4AfIGNFAwBvnQHgD6QaATwB4BzkGiAKLBYE4OAHBwHwASTAK2gcIFwMAGTsAYHgB4OMNAF4AeA85BqU7iAFaAKEGiBl6BYiUCoCwAADg8BotQQ8AHB4APA4nWcPYIUgBTsDAAAAZRoAIGaEBgQAAAHAAAPD5BoBcADweCAYRwPDgAggCAwEIDuiAAHgZBoiyDcEPABwcADw8OQaIAnAN680MePAIzAlIDuwAiADbAEE8AHh4APDwChHA///4CI8OyALCDunGjnh4CAK6A06bAIPAAAAAAAAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCA0NjYgMzkyIAIAAAAAACAGEAAACfAB4eADw8AHgAAAPABwcADw///gAAAADwAA8CAGBAEJAAAA4P//BwBx4eAeIAnIACA5pAAD8AHB4AODhBoBHADweCAbRwPg8A4gOZwCIAlkAQN4A8DwB4GEGgMeAPB4AeB4M200AWg1IAYcAYw0AfHgQc8gBrwAIDyYAAx8A8D4B4HgDwAAAB4B4DwgFkQDBgAABwDh4AHHgCA8rAIgBXABBT4PgHwfAPg+bGcCh+A+B8DuNAPAIAUAAXQEBuAAAAcB4eABwyBjRAMOH/8AP/4Af/4AAAAH/8Af/4AgGEQDAcHgAcMgChQEZCEgNAwADQ/+AB/8AD/4AAAAA/+AD/9oaH01AHSfIAfEAQb/////A8DgA8EgY4wGBAP4AAfwAB+ItQH+AAP8ZGIgByADJ5wAZBoBAYD//yBjQAMnUAIgHCAAZhoAACCrRQPgjVU/cHEgHGQEIGnwAGydIGk0AiAAAAAAAAA5JAIMAAAAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCA0ODUgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCA1MDQgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCA1MjMgMTU2IAIAAAAAACAAAAAAAAAAAAAYEQDAIK/BJAHEGgEHAADgrRsHuAAglxcAAcHBqBoqRgM//iCXOAMDAAB/8eHDpxoOACDONA8AIJxEAwHw8ceAgzIOAHDFGg4gnkYDec+CGgAeKUYDOA6sAiCTFAABBwAxzr4WH/zuNB/8IJtGAwYA7Z0/J0UDPyBjRAMKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNTQyIDUwMiACAAAAAAAgBhAAAg4H///wjAUCPAB//+CEAQE//DgOgAEglBAAKEcDeAD/xhp4ACClRQNwJ0cDcAB4IJuPBgAP+LNL8AHgsE4BAPAAcCCaRAMBHAAf/IQaAQHgAcDEGgHgAHAPjAIglBAAARwAPd6iF9/x5BoBf/jwB7SFpAMgjRQAAh/g+c+AixYf84DPNB/54CCaRAMBP+Hhw6AZKUcD++ADIJmMBgE/78HBtxcHAACoGwEABwPAlDYgMxEAHDhRAQEgJdQBAnxngcBwlAwpRQMBvFCYAiAuEQA8ODwBICYcBQF8ZmHHsgwHAyb1IAegAiA0FQB4OFUBByAlHwX8YODAGCpGA3//ICV0ATD4AqRcMF8AAAAAICbEGDNHA4D//yAlTAsv5QIBOUUDHy+0ACAUQAAB3GH+f7cM//gBxoP//CA4RQMDyAwyrQI+MlAAIBFMADRFA/AgJpQOLz0CBzntB3wvtAAgFEMAHGOGzjR/+OtCf/jgIDdFAw85fA4lfCkgFBgDKdMAHGOO5YMA+uoHACA5RAMp6AEuKACwXy5UACAQPAABHGcOZ7AGAQcAA7jkASA4RQMepAwyFAD0eDJsACALTAABHG6M578FBwAHID5HAxgAADaDHQEAACqgCw0AAAAAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCA1NjEgNDY1IAIAAAAAACAGEAABHG/856gFAQcABzznAeADwKgBICwUAAE8AAB4NUABAgPAAAeANWwAIA5aABxkJ0cDCA8csgcHACA1RAMBPgAA8KQMLxQAAQPgAA8vUAAgFUAAAx/geP/wBmwHAgccHh4ApQEIIDVEAwEfAAHgZA0xDAABAfAAHjFYACATSAACH+A4//CYIwEHPDwPoiUHPCA1RgMPgDgyC/gAyF4gExADK8wAAR/gcAeoWAIH+HwHgJJZB/wgNUYDB8CYCyv8AfEBfDeIDeQEIAccAAIcYOAHAIgnAgfw+APApwH4//8gM2YQA+CQQTNpAj43iA0zuAA5UAABHAHgB7hbAgfh8APwgl0H4CA1RgMB8DitDB+EDzmgAiAIaAABHAfAB6iQAg+H4AHwhiUPwCA1RgMA+DiuDA+DIChUCAsPAAcAAGAAAAAHB4AAcKQBIDb2FgB8NjgaAQAAB8cgJjsaAAAGZBpoOgICAwAAIGIBAAYgN0UDPjY4GgEAAAPviA8gjxEAHzY4GgEAAAH+II8wA50VDzhFAwAglUUDBzn1D3yMHiCPEQADOfUPOCCPMAMgAAAAVrwCDwAAAAAAAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNTgwIDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNTk5IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNjE4IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNjM3IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNjU2IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNjc1IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNjk0IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNzEzIDg3IAIAAAAAACAAAAAAAAAAAAAVEQACILC1JAcgskYDP/4grVIDDwAgr0UDDiCwRAMBHgA4DiCt1gkf/CCvRQM/IHNEAw4AAAAAAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNzMyIDE4NiACAAAAAAAgBhAAATwAOA4gBqgAIIaZAHggsEcDcAB4IK6PBvAAcCCuRAMB4ABwDyCGgAwgBpgCAl/48AfwIAasACCFmwAf+eAgr0cD+8ADIK2PBgcDgCCFMAkgCJYCBwEgCKgAIIahAAcghpwCIAmYAgEHAP//IK3cCQJ32P//wCAJAAQggqYA//wgsUYD4AMgrY4GB4AgsEUDACAAABVEAwACAAAAAAAAAAAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDc1MSAxMDkgAgAAAAAAIAYQAAIHAOADwCAGrAAghZgAILJFAwwgsI0GPCCwRQP8ILBHA/j//yCuZRDgIK9GAw/AIK9EAyCx9RYCILCEHSCFHCAgAAAAAAAAYZQCAAIAAAAAAAAAAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNzcwIDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgNzg5IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgODA4IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgODI3IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgODQ2IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgODY1IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgODg0IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgOTAzIDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgOTIyIDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgOTQxIDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgOTYwIDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgOTc5IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgOTk4IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTAxNyA0MiACAAAAAAAgAAAAAAAAAAAAAAAAAAAAchAACgAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDEwMzYgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxMDU1IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTA3NCA0MiACAAAAAAAgAAAAAAAAAAAAAAAAAAAAchAACgAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDEwOTMgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxMTEyIDc4OSACAAAAAAAgAAAAAADQEAAEfAAAfAAB8Gi+BwfAAA+AAB8AAD50ASAQDAABfAAA+MQJIBDsACAqwAAAFAH/AAP/AAf8AADwAB/wAD/wAH/gAP/AAGAADgABwAA4AAMAAHAA7gGAAM8BGAADrAEHAMAAHAADgA///GQJBP4AB/4AAA4gKnwCIBEoAQAFB//AB//AH/8AA/AAf/wAf/gB//AB/+A1RAMndAMxRAOECQOAD/8AAB4gERgCICrEAAAFD+/AD//AP7+AB/AAfv4A/PwB+/gD9/AgE0QDBe/gD8/AH7+AIBbQCiAnUAMKDwHgHgHgPAeAD/AA8GQBAgPAeAeAZRoMMdQJN48GAAA8ZAkBA8A8ByBfRANwGAAWAeB4B4Ae8AHgDwHAHgeAPA+AeBhhgwwwYcMOOGDDDBhhgw4YYcMGGGwBA3GDDhgxw2wBAAmOGHDBjhgwwwYcYMOGAAB4HgDwHAHgfAPAAH4gJ7gFIBQcAQceAPA8APB4A8A8ZxoDwA5kGg8AeD5ng+z4fd8Pu+HzPh93w+4tLAACj5nw+76cAgR8z4fd8Pu+pBoBPADgeCBgRAMLHADwOADwcAPAMPABwA8nRAMMP//H//h//w//8f/+P//DJy0AH60Bj3wCbAEJ/H//j//w//4AAHAc7iMA/iAUbAUgKdEA8GC3AAoDwCDwAAAPA4APAAA8AAB4B/4A/8Af/AP/gD/wbAEB4B/8AYwBAv8A/+APjgH4B+8BwD/4bAiMIwIAA8AB7iApcAIgFCQBxRoAK0QDCQDwAB4AA+AAfAAHgGTVbQE8bAEJ+AAfAAHgADwAB8AAzQE+bwEB4AAnRQPOIBQcAiAp0AAB4AAA4HzlAfAAAA4njAYJAfgAPwAH4AB+AA/AjgED8O4BH4DPAQD8ACgsAClFAwMgXkYDAeBsLoYxAB6EGgACeAAA8AO8AHuAB3AA7gAd4APcADtsAQLvAB/gAYwBAngA/wAOzAEAAvgAdwAO4AABwAAB4DgA8AAHgAOOIBu4BQwAAAAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDExMzEgODcwIAIAAAAAACANEAAAFAPAAAHAAA+AAPAAAD4DgA8AAPgAAfAHnABzwA44AecAPOADngBxrgEc8IwBCw84AOeAHPADjgB5wAc8bAEMcAADwAAD4DgA8AAPgAeOIA0EAiAvtAAKf8AAA8AB/wAA8AAH/GQaAAgf8AAf4AcOAOHAHjwDx4A4cAcOAPHgHjwBw2wBDI8A8eAOHAHDgDx4B48AcIwBDsA8eAADgAB/wDgA8AH/AAcOIC+MAiANPAEEfwAAB4AB/IUa8IQaAAHAAD/ADw8B4OAcHAODgHh4DwcArAEBwHg4B4wBAh4DwcA4jAEB8B4eAWwBAwAHgAB/AGca/gAPIF9EAwOAAA8AAf6FGviEGgAY4AA/wAIEAEDACAgBgQAQIAIGAEBADAgAgQAQMAIGAGBABAgAgYAQMAICJy0AEIUagKUaHiBfRAMD4AAfAAH/fmgH/oQaAfgAP/AgDZwHBAAAAA8AAH98aAEB/4AcIF5EAwEB4AAeYE9lgx5mGgB8cIMgD0gDAg4AAAHwZ4MHwDwgXkQDAgDwADwAaJUB8AAAD4QaATwAAHggD0ADdSIAhxoDwDggX0UDcH4XAcBtNAeGGh4AbBwgDkwDAh4AAABwbzQB4HggYUQDAvAAAAHghRqDfNEgFEQDAjwAAAB4pRrwIF9HA3gB4CCsRAMEPAB4A+AA8Gw0BwPAB4OADw8AHh4gEtcJeAA8jDQD8AHh///AIA7ICiAsuABlGsAtRQMOIBdHAzwA8CBjRAMCcAeAAHBsNAYBwAeDwA4HgB4gE0QDZKYCeDwA4HAgYIwGBR4A8A8AAHgDnDQFDwPAHgeAHA8gEowGCfAAHgBwPAHgeAHAACBdZBAEHwDwHgAAfIQaB/APAeA+B8A8D4AgED0aASLkIQHwHgPgZAkgXUQDBA+D4D//8D4jNDEH+D4B8HwD4PgHwSAQFCQGAeAAD4PgDwfAZAkgXUQDBAf/wD//8B8jNDEHf/wA//gB//AD/yARRAMIwAAH/8AP/4Af/4AgXtQJBAP/gD//8A8j7C0GP/gAf/AA/+ABIBH4FSLANwL/gAf/AGQJIF2OBgD+csED+HQABA/gAB/AAD8ipDN4ASAPDAAC/gAB/ABkCSAbRAMNAAAAAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTE1MCA0MiACAAAAAAAgAAAAAAAAAAAAAAAAAAAAchAACgAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDExNjkgMTM1IAIAAAAAACAAAAAAAAAAAAAAACMSAAP/gAAFAP/8AAfgH8AjHC0HB//gP4B+AfwD/2ABBn/+A/gH4AAAP4EF4IQEIHsQAMQaA4D//AAP8MUaD2AZAf8B/AeEGgb//gP4D/AAAH+FGvAgezADjBMgAACFRAMN///wAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTE4OCAzNTMgAgAAAAAAIG4SAAP/gAAFgP/8AA/wH8CUEwcP/+A/gH8B/Af/gAEF/gP8D/AAAH+BBfCEBCB7EgAD/HQTA/+A/wP//3QVCH/8AAP/+D//gAH/qwMAAAB0HgXAAH+AAAAAH2wEZAYgeQ4AA/hvE3+A/sQaCP/+AAf/8B//gAD+qAPFGuCkGnA1YAYgegwAuBYgAAAAPEUDwCCaZBADB///gH+AtM0KgD////gD/+Af//8A/5u5H//+ZQH/b51///AghKwTAw///8B/gJzpoAF4zmQaCvwH8AAAP///Af/8AB9nGv//+CCbRAMCgP/8B/jHGvgADyAAAADcRAMGA/4P////wD8AI6AnCw///4D/+APwAAAf//+DbJ0B8AB/gCCNrBMI////+B//wAAA/gCwtiLsMIuc///8IjUuwCCTRQMPxBqQtiDDRAMAAYD///gP8AAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDEyMDcgOTc0IAIAAAAAACBuEAAACAP4D///wH+A////+A//wAAA/gAH+AAAP/+AYBUID+AAf////Af/8B+PBPgP8HgCIHwMACAAYEUDMCACdAgqjAYCH//AAAG1Tn+0TgEf4AA/IDTUCQMODgBwAANkW5IAAcBqFQHgdACMAAJ4AAAAcIUBAHAEpAEFDgA4AAAOAA60ATYUAChEAwj8D//wP////gAH/4AACf4D////4AAA/wAD/HhnbG0gKBwNL0QDAf//gAB/Gh/4f3R5J0UDDoQetBcpRwMP//6sAjAUAChEAwH4D//gNUQDgBkgL0QDBHgABwH///CSAAHBZBoEA8AAAB/8/+QaB/AAD+AADwPAAA+pKwArRQP/MCwDpAIgVkQDAT//gDgpRgMDgYUagMUaH4kY42pEDgExRAMBA//P/yBvRAMDf/+APAAPbDSQAAMDgcADgD9kyAIcPOABwIUaAYcaHgHgLIwGBh4ADgAD/84PB6QyMBQAIFaMBgd//7//8A/9wABwkgAHASdGAzjgeGkHeAAAAeP/+AAAHLiFdAAEA//n//gAHIYajg4gb0QDAw4OP//wH2QakAAzRQPAehg8AIz6aAGkGgQf/g4AADgOOkUDByXMICBOZBABPABwP2QakAAIDgHgA4AADwAAABwnjQYDhRp4sLhkGgQB/+f/8AA/IAFEA2RRB3+A//4AD/AAP8C0ogQ/4AAB/gP8tp///GoDAH9gw3i4YAYgHwwABg4OOABweAHIBrIADhllgx5kGgFw4AHAf8eAA4B6GHgAYbkAaAECAA4AeHAgCkQDmRY/ZBsBAAAAHyKAJ2hsfLkgNEUDHoQaB9wOcHgB3A5wHDllGjyGGv//pRoHhxrwADxx/PFw7wQOAHBwADgedU4POqwTei1/gLgWIEhEAwYP/jhwcHABzA6yADw4eIExRAMBAeAAPixEAwNwDg5gADggc0QDBRjgMCABzgxwkgA4cGQaA3///4AcYOXsD2w0AQHgAB8uRgMP8CBzRAMHAOAA4AAf+ccccJIAf/BlGv9lGuD0t4QaIsQgfHe8aAXmcHAA8A4OeD2sEyBU1gkA4HQvKEQDAuGBwAABJ0QDA3/////wH2w0AQeAAAciFCuHGh/v8IUaPDxFA/wgV0QDBMAAH/HDuHCRAH8ifCADAfAAB4AcbDRmGvg/ZBoBDwBgA3CCZBoHA//n8DAB8A4OHjxEAyOcLQAL/4D/A/gP8B/gf4H+AfgH4B/APwD+A/gP+D/g/4GoAwADwH////////AAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxMjI2IDEyNjAgAgAAAAAAIBMQAAc//z//+AOBw7hwkAAAIgHD///gA/AAB4Ac4OABwH/////4P4AB4AAfAPAB8AAAAAHgAAAD/wPwMAH4Hg4fA/+ODgc22gED/4AABoD+A/gP8B/AfzkgAIAFeAs2LAEgClwAxBoCwfBwA4FwAAKDgcDgB4QaAXDwAcCACQt7j///+H4A8AD4B///gWQaB/4B+DjD+BwODwMgckYDOOOMNHAZJ0UDD6Ya//+lGnNkGgJ8AeAAeMQaDAIOAf44w7gcDgeD/4///5geMRAAIFaMBgc44wOBwAOBwOBwkQAHdAAEHv///4AcOOUaY2QaAjAB4AAwhBoMP/+ADgH/OcecPA4DgDgPIHJFAweEGnROAcDwcA9lGnynGuPAAHksAIQaBwADwAAAB4AHgeBkGgYDzjnDHDgOAQAgdUQDBAOAf/3B8HCQAAMOA///4HiGGhzhxRoDZIMEAAeAAAAHAMQaCQeGOcMeOA4AADgADjG8CagCeCEB////AOSDAYH+A/yJhAApIACwhiArZxA44wdkGgvD+HB//cP4cBwz///gcJxoBhzhwGADgAAHAOQabQEHZIMFAA4PADmADng9RQMBnxT+AHyAAQHAf//+eCUBH8A+AIMD///+gAEB8B/AP4EC4KAhIB8UAAc//w4DgH/5w7hwkAADP/OBwOAgxhrg8ClFAw+MAaQaBD4eAD+AD3A9RAMoaAIBB////6QaAvgAH8AAYBkI+A///4AA//wH//BkAiisACAgJAAHP/8OBwADgccccJAAhRoApBoD4OPgA4B47zQOA8C0TgcAAAH8PgAfgAfwIHVHAwDgH2Uaz2QaAc8ccD9kg+Ya98ApRwMeAeAoRAMDPAAPAAfgZRofOKwTKLQFIEyMBgcA4AfOAAOBzg5wkAACAAOBweB0QgOAHDzgfwApRQM8fBxkgwcAAADgEAAAAAPAIHdEAwMD/gADgdxnGtwOcHy1pBoFH/jgfgADgHD0TgF4AHgAnNHpLwMgdowGB3//gPwAA4H8B3CQACtFAzw2RAMCIAAAGACdaDlgNewcNxwALdQJbJ8gOWQQB3//wHwAA4nYBHCQAAIACAHAGHxLBoAd8OAeAAOA/O808AA8J4wGCHhweDwAD/gOAAA/IAhEAwiAf///B//4AB/gAClGA/4PIiQsNygEIBNgAAd//8D/AAOdwABwkgAA+OQaBhwA4I8AA4H/gLzRAQHgAB59CwF0xghwcDgeAB5+DgAD/zxEAwACD+AAfwAAAAf/8AAAf4AB/Af4AB+Oz//4cgkAAaocAH+YuIgCICEQAAPgAf/AA/lkGnAAAj/4AcA4jDQGHADjj4AAA//wpxoDwD8jSCrEGgY8DgA+P8AAB/45zyAAAABkGiKsITpGAw/gYNRg0yAhMAOECAbgB+fgA/HAAPCSAH/wKEQDCu/D4AAPw/wAA4P///BoYXwFhBoI8Hg8DwD8D/8AA/Agc0QDBR+B8AfhwAHgkAAABH8AAeB4APAAD4AcAP+B+AD/AP+AA4fEGgOAAAABB8Ai1DcIOBwHAfAD///CAH8mhC54HS8MACBVjAYFfwD4B8HAP+CQAAACYAAB//AA8AP/ABwB/gD4P/wAH+DFGv6QGSLMNAMB4DgeB4NxvMAgK0QDC/AAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxMjQ1IDUxMCACAAAAAAAgFBAABuB8AHADgcA/wJAAACQAAAD/4ADwAf8AHAH4ADA/8AAH4AOAAAAAB8AAA8AAAAH/gAAAA8A8DgODwAAH/4AAf///wAA34AEAAw/gAH+AAAAH//AAAH+AAfwH+AAf/4EA+IwGCAH/+AAP4AAA///8jASQAiAfEAAG4HAAEAIBwB8AkAAAAQAAAA4AAPAB/AAcAOAAAD8AAACkGgYAAAABgAAAAf6DARAAA3QBP+0BH6UaDzBFA/CPBwH//OcaA//giAIgfBAACwf//+A/wP/+A//4H///YAEAAfwP4AA/wP8D/gAAD//AAAD+AAeLG/8D/CB8JAPwE4UagIcaD///YAEG+A/wAD+A/wH8KEQDmE+EAvgGIHocACAAAAAvRANrnP/wD6ydpYP+b8Af/8BtwQeFg38ghqwTBAAP8B///4CHm/B//2H1D6jtCf/4B///wD///gAH/2j0fNIgeogTKGgCKUYD4D8sRANxNn8nRgMA/yCFPBoqjAYgAAAAJEUDAIydKhwNAQAB//gqZBAiODEgiGQQBgB/wAD/AAPwD2QaImE08NzQZhoAASJZNPh2oAP/nNIomBQgdiQAI6QtIskw+CpFA4B0NoUaAGQaAfAf/4B0NiB2DAMsWAIgC0QDDfgAAAAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDEyNjQgMzE0IAIAAAAAACBwEAAAEg/wAD+AAP4AB/gP4D//gP/////wH/+AAAH8AA///8AAAP/8B8YC//ggcPQCMkACIACORQMfIKbVCQNkZwEAf/gHfACsAA3wH///AAH/8AP//4AAAH/8iAQE/wB///AH4DLgCiBvTAAED//AfwAB/GQaBsB//wH//A/wH2QC/IDIhAR/AP4AAA/wIG/0AjI8AmUagClFA/iGGoABLkUDgCAAAAABRAMBH//AfyCtHA0DP/+APwABiLQGwD//g//8D+Afbhz//LyIrJ0E4P+A/AAAHyCDrhMH/2zMuBYFwAD//gP/+ACEGpy5JYMn8AA/atMH/yCDRQMPIAAAAAAFRQMHIsU6f4ydAz/g/4AB/iLsKgL/gAAD/CKAKsydC+AAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxMjgzIDM2MyACAAAAAAAgbhAAAAMD///wH8B/AAAD+AAf8D+AAAH8B/9gAAGAAf/8pAIJ//wH+B/gAH///gP8IG70AjI4AsUagGYaD+AsRgP4AIQCZRoPpRr4MggBIG5MACAAAAAtRQPgJ6wTA+A/wAAB/iesEyCWZBBgsgAaP8AA///4B/Af///+Af/8D/A//8D+Af4H8AAf/4AAA/wH+A/gP8D///wH8AAgbmQTMDkCA2KyP4BlGg9kGgH/Af/4YAEDgP8B/Af4hBpgAXi4ZBp0BTAQASBsRAAgAAAAMEcDwAH/ooL//4ydAh//gH8DZ5sf/8Ai7SrwIIxkEAoH4B////8AB/gP8AAAZRr/gJoi6C0EAAAAf////yLILQY/4AD////8D+AgbFwTMjECA4+1//8AYAFgGHQ1gQX/ZNUCAD////59oR9o1nw4jAMgexAAYBmMNGABIACkRAMO//gP8AAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDEzMDIgODY1IAIAAAAAACBuEAAGA/gP8B////8AYAEFAAB//wH///iOFP/8eAAOP////gP4AAAfwAD////4D/BwAiB8DABgGSCvRgMD/2AABwAB////wB///wCMNAYfAAB/+AAH/8DMNAIH//8AP30E4CB8fAZwEwABA/gAD//AAP8AAAf4D+A/gP8AA3ZOP4BwAwMP/+A//4F0TmgDAQAB/AegUmwDIHgMACABRQOAID9FAw5yIwHAdAAgIwwAIAA2RAMFAf//gAHAB/8omQYYkzUwAACJAgOJYAaMAiABEAAgY4wGZxp//8eEGgALB4AD//AA/4AAA8AD/wAH/AAAHgAf8AH//AB/4A+gyj1QAwED+AAfPGQQIEAdDQ8qRQMPZBoIA//AAAPAB/+AH/5mGn/4Zhr/8CAFRAMAAQH8AD//wAH/AAAD8A/wf+H/AAFtnX+UtA8P/+Af/4D8A/wAH/B/gAAD/g8gM6wTBQcBwAOAf//HkYMfZBoEB//gAAfAD2zHCQAAPgB//AH//AH/+CAFRgMAB3/Qf/8BIoQgiu0AB3g2Bv8A//wAD//gAGQZBf//8B/AAAD+ePE9zAcgEngAhxoDgYeEGgANf4ADgAAHgfAAD8AeA+A8D4AAfgDwHgHgAAPAfAAAPCADeAE2RQOAIEhEAwJ/8cADgOUa/2YaDwBkGgACPAHgeAeAAH4B4A8BwAAHgDwAAHgghUUD/2YaB4OtNOdkGgMOAHgAH8BkGgEDgAD+5RocII5FAwOlGscoRAMIOADgcAPAAP4BwAdsNAIAHgAAcCCFjAYDAOHAA4APxBoKh4AHgAAeADgAO8AAAHZnAe6kGnGeACAE5C8gYRwNhxoOA4fc0cUae6QaAYABzgOMNAIAABwAAYSwPpwGhRo/rJ0idC0BAAAH8CKZLYGEgwjwAD8AAAP//+Af4G2d/CAzfTQBbjQ+fy1GA3PAYBgFA4ADjgPAB4Ei7SA8YAI+OAMCAAAAB/9oOQkB/gAH8A//4H+B/gN0tiUNOP+cJgED/AAAIpwxaBtwBSACVAEgC4gABAHBwAOAfH8kFSQH9U7zhxoHgAdlGoPEGngAP2gBphoA/iI3Mf/AfySEICIkNCJUO8QaIgw7AAP//4AAA///8AAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDEzMjEgMTAzOSACAAAAAAAgHxAABAOBwAOAeH64CAAKB4AHHgAeADgA48AAA8AADwAHDgPAB4PHgAAAPGACtAQ7FwAH//B8AwAW/gAH+A//wH+A/gP4AA//////AAP4D///wAAAAAP4AAAf//+AAAP//5AFYAYgKQ0AB2UacNwJBgeAB//AHgA4AacaPwAPhBoF/+AAAHgAA4DUBDsYACBiRwMB//8nqAJlGuBkGgbDwAAHgAH8AA6kGgPwAADwAAcnmAA6SAMgYUUDD2QaAQf///54FGQaA/AeADgDw2hOAQH+AB6kGgH8AAHgIIhEAwIf4f//gIQaAAN//wAHgAeA+B4AOAeDwAAeAAH/ADyEGgTAPAAD4AAPbB4/DQAHaFQDAAD+AAfwfGgBgf4D/HBm/WjgKB0NACA2HA0CP/AcOAAoRwMGAHxkGgUDwAA8AAAPgKYaAB55gg4/NAN0FQP/+AAfwD/IBQE///8BdIIH/+B////8B//wP3NBA/gHYBsCAP4AAA8gMmQQAX94HDhiSg4AjDQEAAA8HgA4D6caA8B4bzSAAB5lBB7YFDsZAAOFGn/IbidFA8DFGh/QnoAZIDZGA/c8ZhoAAIQwcH9kGgcOA8AAeAAAA8BwpRoOaE4gh0YD5xyFGnAnRAMLHB4AOB4DwADwAAABwPCnGg8AHmTSO3QGsAMgYo4GxwgxRAMHPAPAAeAAAAHB4OUaPCCJRAMEBwA8OAAHACyPBj//+HQ0CQHh///DwAcAAA8AfGzsuDA7FAAgYo8GBwA4ZRrw1E4ABQ4AHB4AeD//+AfAAPABwf//wcAHBwAPdWp4OygD0AMDA//wAB/gKWUQA4ydMmQQAgH+AAAHiITMByAmGADFGuAnRgM8DqUagOQaAQ8HgA50aiAI8AEIH//A/gAB+AAPwABtt/xkFQV/gAP8AAAf8HLcAAciYieAf2QCbAMgLgwABAcAeDgwBwHvNA8APGAyDQPADwAAcAPAAB4B4A8HgB50aiAKRQOAIlwqBgAP4AAA////+GUWfyJMJaUCAIQaAT+A/wGMHXQDICwPAAcAcGUa/Mw0AAcPgHgPAPAAA8AeAAB4A8AADgHwHgPAPgPAIhwkIAbiAR//IF5EAwLwODAAAyS0KgQHgAfA+AfBZBoOP//gPg+AAA4A+D4D4HwH//54NCAFSAMgX0QDBAHgOHAAD4+MSgkHgAP/8AP/4AADwD8iyCJg7wJ//AH/+GQaImgzIARIAyBfRQMDZRo/tHQEB4AB/+AB/yK4NwI///AP/mQaBj/4AP/wB//+AyCIRAMEB8A/8AP+AIKuA4B8AAV/AAADwB//4GmSDnR5Aj/gA//+IAXAN3M4H//AhYMfIANkEAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxMzQwIDQzNSACAAAAAAAgHxAABwcfgD/wf/gAH+AgHyQBvAcACAP/4A/////8Af///+AAP//////wB8AAf4B/aAEE/4A///wAA2kBAGQDrAYgLRQABgcfAB/gf+AAByAmRwMH//B/GP4AB2QaAA5//wAAB/AP4AB/gP4D///wH8B/gP4AAA///8AA//4D+CAtLAO0CQcHDAAAAH4AAADAvAEgHxQAMUUD+CBNRAMgHwQDLvwAIAAAeEUDgSA/ZBAuHAwgHzwAAQP/+ABgtaydCP//AAAP/B/wAD+BfLkC+D/g/4F4n2ydAX/8AfwgH7QBIEX9AB94FQYB/Af4H+A///9wzwLwH8AA/3APCB///4D///wAAB//i6sH//B4AiB/DAACD///gABlGg8vRANoA4UaDyAAAADXRAOMnQYD/g/4D/B///6MnQM/4AD/gABqnP/AhoMf/yNgLCCErRMHIqQwjQD4I4QtAgAD/AAffwH+AABjGH///3wAIpgxAf4D/A8ggvQWLEQDAoAAAAP4IvIw//8jqiDgAHs2B//wcxz+A/ggAIREAwwP8AAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDEzNTkgMzgyIAIAAAAAACBvEgAH/+AACPgP//+AAAAD+AAPaAIABf4AAA//4AB///4AB//wH/////4D+A/wIG/8AjA8AiC8RAMBH///wIw0YTL/LI0GPyCJjAZoTAHgAAH/bEwN8H//AP4AAAf//+AAAf4AA3wABH+B////+B9mAv//IITUCWYawABgGQMP/+A//4CIM2w1eGd9aIBlGg9kAiAAAADbRQMHZYOBL2UQAGWDHyCKZBAMA/gAP8A/AP/8AAAf/+D/udD/ZwL///zDGfwP8I4EAAAghMwgA/gAH8B/gKUawCLMI525f5C2xxr4D/BsBHg3IIMUJChGAw//LkQDKBgaIAAAAAlEA4ydKxwNcbbwKxwNI+wnIIFkEAkB//gH/8A+AP/8A/AjoDcC//gD//+EAgf//+AH/4A/AP//ZwPAPgAiNS7gMIQ1IG5HAAP/+KIx/Ad8FgP/gAH8B/iTtv4D/G0Vf3k3DyPkNA/+AAf4AAAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDEzNzggMzA0IAIAAAAAACBuEAAPA//4D//AAAD//Af4D////4ABgAEDwAAA/gP4bBUEf4D//AAP/28E/gAHiAJ4AiB5DAAgAABeRQMBfWgfKh0NAf1ogf1oASCFHQ0BZIMF4AAB//4P+D9kGgMA+APwD/9kAriABH/B//wAB/+GAgAPIIJlEACrnP/+A2udwH+AkJh2Nf/8igF//4ABhAIB//gP8JACIHwQACAAAAD8RgMP+LqYB/wi8Sb/rJ18uIucAAA/rJ2EAiCErBMFA/////A/wP+AAAXwP//+Af/4B3IBgf8ipyofwABw72ACAsD/A/4AIIL0Fmca4D+AaBYD///gP///iO5o7SPNIB8kWC54AwGA/wH8IAAAACZEAwACgP8B/AAP8AAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDEzOTcgMzU3IAIAAAAAACBuEAAFA////+A/wP+AAAXgP///Af/8D3ABCgD+A/gAAB/AAAD//AdgAgTA/gH8AA/wIG78AjA4AgAHA/wP8B///4H/AA///+AAf/8B///4AD/gAGQaBAfgAD//AP9gGQQ///+AAAP4IINFA/iEGgGA/gAHKUQDaTP+nxc//4CFGh8gAAAA1UUDB4ydL2UQAeWDgSllEPwghKwTCQAf8AAA/wP8AB/4P3/OB//4cLwJfwAAB/gfwD///wAAZNMEf8D+AAP//yCCPBoE+AAP4AAA/5TnAx/////+A6Ua/2UaD2zuYAECAAA/gP8gAAAA5EQDnJkgm2QQI68w///wIxAxfLcH4AAP/wD/APgH+KydAQH//+ByAwD/IIb1FgAiXC186Q3/4AAAAf///AAAH/+A/wH85Bp70B/Af2QCIIU8GitFAwAieDQgy0QDDP/wAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTQxNiAzNzYgAgAAAAAAIG4QAAABA/gAAB///4D+A/gP/+AAAAD//4QCAAGA/wH8B/gP4D///wAD///wH8B/ZgL/8CBu/AIwOAIgz0UDHyCSjAYBAfgAAGRLAfwB+AdpSgH0Tg9/g/4P+D/wf///gAf///g/4P8ghtQJAwAAB///wNRRCh//gH8AAAAH8B//gAGFa/8oAACEa3Ae0AUgeRkADytEAwL/AAAAD2UaACAAAADvRwM//4BkgwcH8D//wAH+B/wPKKQTBP//wP4B/AcjWCEgeZQTZBMJA//4H/A////+A/gAIhgkZBoiWCQJ//8B////8AA/wP//dJ8EP+B/gAAD/GgGIH4OAAP/JPAmphrAAIQajDPHGoD//mYaH8BlGvggfjQDeBMgAAAANkYDH/8uZxDgAD/EgwE/4H8AIImsEwP/wAAB//wjMzE//wAiDDgNAH///wAH/AAAH8AA/wH/+HCfAALAAAH////gAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTQzNSAzNDMgAgAAAAAAIG4QAAAHA//4D//AAAD//Af/8AAAf/8AA/gAAAA//6ABAh/AAP8BaAQE//+AAAH//2wEIG4EAy44AiAAAABGRAMJ/AAAP+AAfwP/+Af/ZYMDIIRkEAsAD/gP8D//AAP///wfwGydBgAH/+AAP/+B/GAYDv//gAH//gAAH//gAH/////8LmQRIHI8AAIH+A/gP38W//gPdhYAAHi4AT//gP7FGgB4GAUf/8AA/////2S7IHIQAytIAiAFRANs1iAAAAALRQMfKmUQgStkECCNHw0HwD9yfv//lLZtnf8nRAB40HfQB/+AsQTgK1gRIHQwAAMH+AAAP8BozQMP/+AAAP+FGuBkAiI3Lh//gHa28AAjWy4AAA9kASB0HAMoUAKFGoBozStGA4D/I3wxxBp70H//ACAAAFVEAwAB/wAAAA/wAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTQ1NCAzOTUgAgAAAAAAIG8QAAAEB/gAAD+A////+A//4AAA/wAAB///4GQCBfwH//Af/4ABbAMHAAAAf/8AAAAP8CBv/AIwPAIDA/AAAH/gdBYABQf/wAAA/gAAD///8H+Af//4A//4P//gKEQDAoAAAA/gMAQBIHFHAA///2QxB/gAAAA//4AAA/+oMwAC/gAAAB/gP////gP8D///wH+B/gBgOiBxAAMvRAI0RAN2NQAPpRr4hRqAIAAAANNFAx+tnfyNnQBtneB40GydxIONnT8ghqwTbLUCAD/A//6A6wEAAAABZBti6gH/vLls7mQBAQD/Afwgg/QWpRqAMEUD/yAAAADlRQPgK60TA3S2AwAAAP8D/3aeP/9snSMMMQF/A/wHgAEvZCggbUAABA/4AB///4BxEh8iOTH/cLYKH///gf/////gH8AAAWgcAg//wAABiBxgBSB9DQAHKEQDeRYA5BoiEzj/8B8kyTQAqANwNiB9NAN0EyALRAMO/AAAAAAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDE0NzMgMzQzIAIAAAAAACBvEAAEB/gAH///gHgSBg//wAAA///4AIQCCv/////wH8AAAP4AAACpA/x0BCCADAAgAJxFA4H1TgEgjtQJDAH8D//wAAD+AfwD8A/wP5xpAAUAD/B///8AB//8AAA////+AfgAD/A//2psB+AggBgNCwP4D//gAAD/AfwH+A/g5BoD4D///wADbIRkGgoD+AAP4D//gP//+A/wIAAAAMxFA/w5ZRDwrJ3Fg4EghmQQeM4D////APgDxAEC+APwB8BsnQL//+AAD5IC+AeYAAH///ADIIL3Fv/4H3gVIuwmBfAfwH////wHqTMBIhQnAR/AAAGIM3AEaO0ggPAWcM6cMCpFA/iQTeQaYusP8CAAAADURwMB//xwfiIQOw4P4B/g/////g/8AAB///4A+HSFIhQrAf/8D+BwBA/8AAAAAAAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDE0OTIgMjg1IAIAAAAAACBvEAAABgf/8AAAAAH+A//4AB///4H/////8B//wNwUAT+AAADIAwGAAAP/kAXIAyB3GAClGgDlGoDFGoDcFSAAAADdRQMDm5cB/gcprRPgKa0TwK+dP///jZ3gxIYgfBgADx/gAH//Af//+A/gAAD/A/4AAHi4Bv/+AAAH4AA//5mgD2igZAMgfCQD8RMPK0YDAfwoRAMDD/AAP/+AYLsgAAAA4EUD8KydLmQQIJKsE22eAYSzABAf/4D///wD8AAf4AAB//wD///gP8AA/gAH+AA/4AAB/gADIpwufAUgggwAKUQDBwf4AB/AAAD//AdlGoCkGmQCiBsggiwDqBQgAKxEAwsAAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTUxMSAzNjcgAgAAAAAAIHYRAP58EgAGH/+A///8B/gAH8AAAP/8B///4D+AAP4AxAKAAXwEIIQMAIUaPzJFAwGDGT/AAGkb8CCBMgMB/4AABgAD//gAD//gf5QBAeAfwD+MNAj4AAAAf/4AB////2YC//wggUIDAAOLGP+AAYUawKQaAvAfwH+AdE5pMv/EGgF/gP//ZBwgf1ADIAAAAENEA4ydK2YQAP8gj68TB///KK4TPgDQoN4A/8CEAmgcIH6xEwOJzH91tw9xtoGQtiLNIP6boMAA/6jWZuwD/yCDRAOIzChEA7jQN0QDlAUgfZEGA4wUIAAAakUDAS9kEGQCjFQgiB0NByTILQT+D//4P+AAfBcE////4AD/g5y4AuAAAf8HIIWsE5rQgAF0uGicAgH///gfbRj+IoAxBgA//4H+A/wP8IgCbAQgfYAGAwAAAAP4D2DrLEUDDypEAwGA/gP4KkQDCQAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTUzMCAzMDggAgAAAAAAIG4QAAACA/gP///Af4AB/AAAAB/AAAAB//9oAgAD///+A//4AAA//4D+A/gP8B//////bAQgbvwCMDgCIAAAX0YDA/7caAED///4kGb8aAMA/wf4B+CoAjDUCiBxRAD8aAT///gH/+A/fH8D///wAD/AZIME///gP8AA/2eEAAB/jQPgIHEIAy1EAilFAw8qRQOA5RqALEUD8C38ACBxOAAgAAAANEUD/CxkEAF//gP/bJ1kgyP0I6ydIIlkEHgXCv//wAAAA/4AD/AAP4AjgCcEAAAAfwAAB5y2A8D//wAP/yCJRQMBtBYBAAAB/C1GA4AAtB0CgP/+AAcgAAAAz0UDByQMOyllEAcipCpsnWKbfwDEgwACwP/+AAf/8AAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDE1NDkgMjczIAIAAAAAACBuEgAD+GASA3+AAf///2gBAAR//wP4AB/AP/8A/wAAAA///8AA/AP/wAAB/Af/8HgFIHwMACpEA3QVCP/+A/gAD+A//4D+pxqAAP4gAAAA2UUD/GCXrJ0gpmQQoLOUtwHwD/8AeAEM8A/gH/+A////8A///4B/aAInDQDgYCAgfAwAxLMDgAH8AA/wnBgE/AfwD+AAf6QaAeA/gP+IAwEAAAABYLsgfDADkBMyRQP45hr4DypFAwAgAAAA0EQDIswtB////wAA+AAH4A9stQT4A/APwAA/fLgD8A/AH4B+iAN6iPwBInQuZAEgAAAAHgwAAAIAAAAAAAAAAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTU2OCA0MiACAAAAAAAgAAAAAAAAAAAAAAAAAAAAchAACgAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDE1ODcgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxNjA2IDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgMTkgMTAgMTYyNSA0MiACAAAAAAAgAAAAAAAAAAAAAAAAAAAAchAACgAAAAAAAAAAAAAAAAARAAAKR0cgMjEwIDE5IDEwIDE2NDQgNDIgAgAAAAAAIAAAAAAAAAAAAAAAAAAAAHIQAAoAAAAAAAAAAAAAAAAAEQAACkdHIDIxMCAxOSAxMCAxNjYzIDQyIAIAAAAAACAAAAAAAAAAAAAAAAAAAAByEAAKAAAAAAAAAAAAAAAAABEAAApHRyAyMTAgOCAxMCAxNjgyIDM1IAIAAAAAACAAAAAAAABhEAAMAAAAAAAAAAAAAAAAAAAAEQAACkZPUk0KUFJJTlQK';
      // let cpcl = uni.base64ToArrayBuffer(cpclBase64);

      uni.showLoading({
        title: '正在发送指令...',
        mask: true,
      });
      // 写入指令
      await this.device.write(cpcl);
      // uni.hideLoading();

    },
  },
};
</script>

<style>
button {
  margin-top: 30rpx;
  margin-bottom: 30rpx;
}
</style>
